[package]
name = "term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
console = "0.15.8"
portable-pty = "0.8.1"
winit = "0.29.10"
winit_input_helper = "0.15.3"
rusttype = "0.9.0"
glyph_brush = "0.7.8"
wgpu_text = "0.8.6"
wgpu = "0.19.1"
env_logger = "0.11.1"
pollster = "0.3.0"
