[package]
name = "term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
portable-pty = "0.8.1"
termwiz = "0.22.0"
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
dioxus-signals = "0.4.3"
tokio = "1.36.0"
web-sys = {version =  "0.3.68", features = ["ResizeObserver", "ResizeObserverEntry"] }
futures = "0.3.30"
