[workspace]
members = ["gui", "term", "hooks", "config_watcher"]
resolver = "2"

[workspace.dependencies]
hooks = { path = "./hooks" }
term = { path = "./term" }
gui = { path = "./gui" }
config_watcher = { path = "./config_watcher" }
