unstable_features = true
tab_spaces = 4
use_field_init_shorthand = true
fn_single_line = true
imports_granularity = "Module"
normalize_comments = true
group_imports = "StdExternalCrate"
use_try_shorthand = true

single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
max_width = 100
