[package]
name = "pretty_hooks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dioxus = { workspace = true }
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
log = { workspace = true }
