[package]
name = "pretty_hooks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dioxus = { workspace = true }
dioxus-document = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.114"
log = { workspace = true }
tokio = { workspace = true }
